// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PlayMidiController from "./play_midi_controller.js"
application.register("play-midi", PlayMidiController)

import SearchMidisController from "./search_midis_controller.js"
application.register("search-midis", SearchMidisController)
